sudo: true
language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "ndk-bundle"
  - yes | sdkmanager "platforms;android-28"

script:
  - sudo apt update
  - sudo apt install tree pastebinit -y
  - ./gradlew assembleDebug
  - tree | pastebinit
